services:
  - name: attendance-api
    type: web
    env: node
    rootDir: app
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
    plan: free
    autoDeploy: true 